workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_PROJECT_NAMESPACE != "openldap"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "OPENLDAP_REL_ENG_2_5" && $CI_PROJECT_NAMESPACE != "openldap"'
      when: never
    - when: always

stages:
  - build

build-no-threads-no-slapd:
  stage: build
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y build-essential autoconf groff-base libsasl2-dev libssl-dev
    - autoreconf
    - ./configure --without-threads --disable-slapd
    - make depend
    - make

build-openssl-heimdal-lloadd:
  stage: build
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y build-essential pkg-config automake libsasl2-dev heimdal-multidev libssl-dev libltdl-dev groff-base unixodbc-dev libwiredtiger-dev libperl-dev heimdal-kdc libsasl2-modules-gssapi-heimdal sasl2-bin libevent-dev
    - autoreconf
    - ./configure --enable-backends=mod --enable-overlays=mod --enable-modules --enable-dynamic --disable-ndb --enable-balancer=mod
    - make depend
    - make
    - ulimit -n 4096 # back-monitor takes a while scanning a long connections array
    - make test
  artifacts:
    name: testdir
    when: on_failure
    expire_in: '1 week'
    paths:
      - tests/testrun/

build-gnutls-mit-standalone-lloadd:
  stage: build
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y build-essential pkg-config automake libsasl2-dev libltdl-dev groff-base unixodbc-dev libwiredtiger-dev libperl-dev krb5-user krb5-kdc krb5-admin-server libsasl2-modules-gssapi-mit sasl2-bin libgnutls28-dev libevent-dev
    - autoreconf
    - ./configure --enable-backends=mod --enable-overlays=mod --disable-autoca --enable-modules --enable-dynamic --disable-ndb --enable-balancer=yes
    - make depend
    - make
    - ulimit -n 4096 # back-monitor takes a while scanning a long connections array
    - make test
  artifacts:
    name: testdir
    when: on_failure
    expire_in: '1 week'
    paths:
      - tests/testrun/
